name: "Build Harbor ARM64"

on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push images to registry'
        required: false
        # 修正: 使用布尔值 false 而不是字符串 'false'
        default: false
        type: boolean

jobs:
  build-arm64-package:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout Harbor Source Code
        uses: actions/checkout@v4
        with:
          path: src/github.com/goharbor/harbor

      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: 'space-delimited'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        if: github.event_name == 'push' || github.event.inputs.push_images == 'true'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-east-1

      - name: Login to Docker Hub
        if: github.event_name == 'push' || github.event.inputs.push_images == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Setup Go environment
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Determine if Base Image needs to be rebuilt
        id: build_base_check
        # 这个步骤不需要指定工作目录
        run: |
          if [[ "${{ contains(steps.changed-files.outputs.all, 'make/photon/Dockerfile.base') }}" == "true" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "build_base=true" >> $GITHUB_OUTPUT
          else
            echo "build_base=false" >> $GITHUB_OUTPUT
          fi

      - name: Build ARM64 Package
        id: build_package
        # 修正: 明确指定此步骤的工作目录
        working-directory: src/github.com/goharbor/harbor
        run: |
          set -ex
          
          # --- 准备构建参数 ---
          TARGET_BRANCH="$(echo ${GITHUB_REF#refs/heads/})"
          RELEASE_VERSION=$(cat ./VERSION)
          PACKAGE_VERSION="${RELEASE_VERSION}-build.${GITHUB_RUN_NUMBER}-arm64"

          if [[ $TARGET_BRANCH == "main" ]]; then
            ASSETS_VERSION=$PACKAGE_VERSION
            TARGET_BUCKET="harbor-builds"
          else
            ASSETS_VERSION="${RELEASE_VERSION}-arm64"
            TARGET_BUCKET="harbor-releases/$TARGET_BRANCH"
          fi

          BASE_TAG=${TARGET_BRANCH#release-}
          if [[ $TARGET_BRANCH == "main" ]]; then
            BASE_TAG=dev
          fi

          MAKE_FLAGS="GOBUILDTAGS=include_oss \
            BASEIMAGETAG=${BASE_TAG} \
            VERSIONTAG=${ASSETS_VERSION} \
            PKGVERSIONTAG=${PACKAGE_VERSION} \
            TRIVYFLAG=true \
            EXPORTERFLAG=true \
            GOARCH=arm64 \
            BUILDPLATFORM=linux/arm64"
          
          if [[ "${{ steps.build_base_check.outputs.build_base }}" == "true" ]]; then
            MAKE_FLAGS+=" BUILD_BASE=true PUSHBASEIMAGE=true REGISTRYUSER=${{ secrets.DOCKER_HUB_USERNAME }}"
          fi

          # --- 执行构建 ---
          sudo make package_offline $MAKE_FLAGS
          sudo make package_online $MAKE_FLAGS

          # --- 产出物处理 (现在我们在正确的目录里) ---
          OFFLINE_BUNDLE=$(ls harbor-offline-installer-*.tgz)
          ONLINE_BUNDLE=$(ls harbor-online-installer-*.tgz)
          
          echo "offline_bundle_path=$PWD/$OFFLINE_BUNDLE" >> $GITHUB_OUTPUT
          echo "online_bundle_path=$PWD/$ONLINE_BUNDLE" >> $GITHUB_OUTPUT
          echo "assets_version=${ASSETS_VERSION}" >> $GITHUB_OUTPUT
          echo "target_bucket=${TARGET_BUCKET}" >> $GITHUB_OUTPUT

      - name: Upload ARM64 packages to S3
        if: github.event_name == 'push' || github.event.inputs.push_images == 'true'
        # 修正: 明确指定此步骤的工作目录
        working-directory: src/github.com/goharbor/harbor
        run: |
          source tests/ci/build_util.sh
          TARGET_BUCKET="${{ steps.build_package.outputs.target_bucket }}"
          
          uploader "${{ steps.build_package.outputs.offline_bundle_path }}" "$TARGET_BUCKET"
          uploader "${{ steps.build_package.outputs.online_bundle_path }}" "$TARGET_BUCKET"
          
          cp "${{ steps.build_package.outputs.offline_bundle_path }}" harbor-offline-installer-latest-arm64.tgz
          cp "${{ steps.build_package.outputs.online_bundle_path }}" harbor-online-installer-latest-arm64.tgz
          uploader harbor-offline-installer-latest-arm64.tgz "$TARGET_BUCKET"
          uploader harbor-online-installer-latest-arm64.tgz "$TARGET_BUCKET"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: harbor-arm64-packages
          path: |
            ${{ steps.build_package.outputs.offline_bundle_path }}
            ${{ steps.build_package.outputs.online_bundle_path }}
          retention-days: 7

      - name: Push ARM64 Docker Images
        if: github.event_name == 'push' || github.event.inputs.push_images == 'true'
        # 修正: 明确指定此步骤的工作目录
        working-directory: src/github.com/goharbor/harbor
        run: |
          ASSETS_VERSION="${{ steps.build_package.outputs.assets_version }}"
          
          tar -xvf "${{ steps.build_package.outputs.offline_bundle_path }}"
          docker load -i harbor/harbor.${ASSETS_VERSION}.tar
          
          docker images "goharbor/*:${ASSETS_VERSION}" --format "{{.Repository}}:{{.Tag}}" | while read -r image; do
            echo "Pushing ${image}"
            docker push "${image}"
          done