name: "Build Harbor ARM64"

on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push images to registry'
        required: false
        default: false
        type: boolean

jobs:
  build-arm64-package:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout Harbor Source Code
        uses: actions/checkout@v4
        with:
          path: src/github.com/goharbor/harbor

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event.inputs.push_images == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Setup Go environment
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      # --- 终极补丁脚本：一次性修复所有已知问题 ---
      - name: Find and Patch all Dockerfiles for ARM64
        working-directory: src/github.com/goharbor/harbor
        run: |
          set -ex
          echo ">>> Stage 1: Globally patching all Dockerfiles to use a generic ARM64 base..."
          TARGET_FILES=$(grep -rl 'FROM \${harbor_base_namespace}/.*-base:\${harbor_base_image_version}' ./make)
          
          for dockerfile in $TARGET_FILES; do
            echo "Patching ${dockerfile} with generic base..."
            sed -i 's|FROM ${harbor_base_namespace}/.*-base:${harbor_base_image_version}|FROM photon:4.0|g' "$dockerfile"
          done

          echo "\n>>> Stage 2: Applying specific patches for individual components..."
          DB_DOCKERFILE="make/photon/db/Dockerfile"
          PREPARE_DOCKERFILE="make/photon/prepare/Dockerfile"
          LOG_DOCKERFILE="make/photon/log/Dockerfile"
          REDIS_DOCKERFILE="make/photon/redis/Dockerfile"

          echo "Applying 'postgres' patch to ${DB_DOCKERFILE}..."
          sed -i 's|FROM photon:4.0|FROM postgres:14-alpine|g' "${DB_DOCKERFILE}"

          echo "Applying 'redis' patch to ${REDIS_DOCKERFILE}..."
          sed -i 's|FROM photon:4.0|FROM redis:7-alpine|g' "${REDIS_DOCKERFILE}"

          echo "Applying 'pipenv' patch to ${PREPARE_DOCKERFILE}..."
          awk '/COPY make\/photon\/prepare\/Pipfile.lock/ {
            print "RUN tdnf -y install python3 python3-pip && pip3 install pipenv"
          } 1' "${PREPARE_DOCKERFILE}" > "${PREPARE_DOCKERFILE}.tmp" && mv "${PREPARE_DOCKERFILE}.tmp" "${PREPARE_DOCKERFILE}"
          
          echo "Applying 'logrotate' patch to ${LOG_DOCKERFILE}..."
          sed -i '/\/etc\/cron.daily\/logrotate/c\RUN tdnf install -y logrotate && rm -f /etc/cron.daily/logrotate' "${LOG_DOCKERFILE}"

          echo "\n>>> Stage 3: Globally creating 'harbor' user and group where needed..."
          for dockerfile in $TARGET_FILES; do
            if grep -q "FROM photon:4.0" "$dockerfile"; then
              echo "Adding user/group creation tools and 'harbor' user/group to ${dockerfile}..."
              awk '/FROM photon:4.0/ {
                print;
                print "RUN tdnf install -y shadow && groupadd --system --gid 10000 harbor && useradd --system --uid 10000 --gid harbor harbor && mkdir -p /home/harbor";
                next
              }1' "$dockerfile" > "$dockerfile.tmp" && mv "$dockerfile.tmp" "$dockerfile"
            fi
          done

      - name: Build and Package Harbor for ARM64
        id: build_package
        working-directory: src/github.com/goharbor/harbor
        run: |
          set -ex
          
          # 步骤 1: 准备版本号
          RELEASE_VERSION=$(cat ./VERSION)
          PACKAGE_FILENAME_VERSION="${RELEASE_VERSION}-build.${GITHUB_RUN_NUMBER}-arm64"

          # 步骤 2: 构造 make 命令参数
          MAKE_FLAGS="GOBUILDTAGS=include_oss \
            VERSIONTAG=${RELEASE_VERSION} \
            PKGVERSIONTAG=${RELEASE_VERSION} \
            TRIVYFLAG=true \
            EXPORTERFLAG=true \
            GOARCH=arm64"

          # 步骤 3: **关键修正** - 首先编译所有 Go 二进制文件
          echo "--- Step 3.1: Compiling all Go binaries for ARM64 ---"
          sudo make compile $MAKE_FLAGS

          # 步骤 4: 构建所有 Docker 镜像 (现在可以找到已编译的二进制文件了)
          echo "--- Step 3.2: Building all Docker images ---"
          sudo make build BUILD_BASE=true BASEIMAGETAG=${RELEASE_VERSION} $MAKE_FLAGS

          # 步骤 5: 为所有构建好的镜像打上 'dev' 标签作为双保险
          echo "--- Step 3.3: Tagging all built images with 'dev' to pacify the packaging script ---"
          docker images "goharbor/*:${RELEASE_VERSION}" --format "{{.Repository}}:{{.Tag}}" | while read -r image; do
            new_tag="${image%:*}:dev"
            echo "Tagging ${image} as ${new_tag}"
            docker tag "${image}" "${new_tag}"
          done
          
          # 步骤 6: 现在执行打包，Makefile 无论找哪个标签都能找到
          echo "--- Step 3.4: Packaging all components ---"
          sudo make package_offline $MAKE_FLAGS
          sudo make package_online $MAKE_FLAGS
          
          # 步骤 7: 重命名最终产物
          mv "harbor-offline-installer-${RELEASE_VERSION}.tgz" "harbor-offline-installer-${PACKAGE_FILENAME_VERSION}.tgz"
          mv "harbor-online-installer-${RELEASE_VERSION}.tgz" "harbor-online-installer-${PACKAGE_FILENAME_VERSION}.tgz"

          OFFLINE_BUNDLE="harbor-offline-installer-${PACKAGE_FILENAME_VERSION}.tgz"
          ONLINE_BUNDLE="harbor-online-installer-${PACKAGE_FILENAME_VERSION}.tgz"
          
          echo "offline_bundle_path=$PWD/$OFFLINE_BUNDLE" >> $GITHUB_OUTPUT
          echo "online_bundle_path=$PWD/$ONLINE_BUNDLE" >> $GITHUB_OUTPUT
          echo "assets_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT

      - name: Upload build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: harbor-arm64-packages
          path: |
            ${{ steps.build_package.outputs.offline_bundle_path }}
            ${{ steps.build_package.outputs.online_bundle_path }}
          retention-days: 7

      - name: Push ARM64 Docker Images
        if: github.event.inputs.push_images == 'true'
        working-directory: src/github.com/goharbor/harbor
        run: |
          ASSETS_VERSION="${{ steps.build_package.outputs.assets_version }}"
          OFFLINE_BUNDLE_PATH="${{ steps.build_package.outputs.offline_bundle_path }}"
          
          tar -xvf "${OFFLINE_BUNDLE_PATH}"
          docker load -i "harbor/harbor.${ASSETS_VERSION}.tar"
          
          docker images "goharbor/*:${ASSETS_VERSION}" --format "{{.Repository}}:{{.Tag}}" | while read -r image; do
            echo "Pushing ${image}"
            docker push "${image}"
          done