name: "Build Harbor ARM64"

on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push images to registry'
        required: false
        default: false
        type: boolean

jobs:
  build-arm64-package:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout Harbor Source Code
        uses: actions/checkout@v4
        with:
          path: src/github.com/goharbor/harbor

      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: 'space-delimited'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- (已删除) Configure AWS credentials 步骤 ---
      # 这一步导致了错误，并且我们不再需要它

      - name: Login to Docker Hub
        if: github.event.inputs.push_images == 'true' # 注意: 这里只在手动触发并选择推送时才登录
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Setup Go environment
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Determine if Base Image needs to be rebuilt
        id: build_base_check
        run: |
          if [[ "${{ contains(steps.changed-files.outputs.all, 'make/photon/Dockerfile.base') }}" == "true" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "build_base=true" >> $GITHUB_OUTPUT
          else
            echo "build_base=false" >> $GITHUB_OUTPUT
          fi

      - name: Build ARM64 Package
        id: build_package
        working-directory: src/github.com/goharbor/harbor
        run: |
          set -ex
          
          # --- 准备构建参数 ---
          TARGET_BRANCH="$(echo ${GITHUB_REF#refs/heads/})"
          RELEASE_VERSION=$(cat ./VERSION)
          PACKAGE_VERSION="${RELEASE_VERSION}-build.${GITHUB_RUN_NUMBER}-arm64"

          if [[ $TARGET_BRANCH == "main" ]]; then
            ASSETS_VERSION=$PACKAGE_VERSION
          else
            ASSETS_VERSION="${RELEASE_VERSION}-arm64"
          fi

          BASE_TAG=${TARGET_BRANCH#release-}
          if [[ $TARGET_BRANCH == "main" ]]; then
            BASE_TAG=dev
          fi

          MAKE_FLAGS="GOBUILDTAGS=include_oss \
            BASEIMAGETAG=${BASE_TAG} \
            VERSIONTAG=${ASSETS_VERSION} \
            PKGVERSIONTAG=${PACKAGE_VERSION} \
            TRIVYFLAG=true \
            EXPORTERFLAG=true \
            GOARCH=arm64 \
            BUILDPLATFORM=linux/arm64"
          
          if [[ "${{ steps.build_base_check.outputs.build_base }}" == "true" && "${{ github.event.inputs.push_images }}" == "true" ]]; then
            MAKE_FLAGS+=" BUILD_BASE=true PUSHBASEIMAGE=true REGISTRYUSER=${{ secrets.DOCKER_HUB_USERNAME }}"
          fi

          # --- 执行构建 ---
          sudo make package_offline $MAKE_FLAGS
          sudo make package_online $MAKE_FLAGS

          # --- 产出物处理 ---
          OFFLINE_BUNDLE=$(ls harbor-offline-installer-*.tgz)
          ONLINE_BUNDLE=$(ls harbor-online-installer-*.tgz)
          
          echo "offline_bundle_path=$PWD/$OFFLINE_BUNDLE" >> $GITHUB_OUTPUT
          echo "online_bundle_path=$PWD/$ONLINE_BUNDLE" >> $GITHUB_OUTPUT
          echo "assets_version=${ASSETS_VERSION}" >> $GITHUB_OUTPUT

      # --- (已删除) Upload ARM64 packages to S3 步骤 ---
      # 我们使用下面的 upload-artifact 步骤来代替它

      - name: Upload build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: harbor-arm64-packages
          path: |
            ${{ steps.build_package.outputs.offline_bundle_path }}
            ${{ steps.build_package.outputs.online_bundle_path }}
          retention-days: 7

      - name: Push ARM64 Docker Images
        if: github.event.inputs.push_images == 'true'
        working-directory: src/github.com/goharbor/harbor
        run: |
          ASSETS_VERSION="${{ steps.build_package.outputs.assets_version }}"
          
          # 注意：这里的 offline_bundle_path 是一个绝对路径，需要处理
          OFFLINE_BUNDLE_PATH="${{ steps.build_package.outputs.offline_bundle_path }}"
          tar -xvf "${OFFLINE_BUNDLE_PATH}"
          docker load -i harbor/harbor.${ASSETS_VERSION}.tar
          
          docker images "goharbor/*:${ASSETS_VERSION}" --format "{{.Repository}}:{{.Tag}}" | while read -r image; do
            echo "Pushing ${image}"
            docker push "${image}"
          done